apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterinstanceclasses.services.apps.tanzu.vmware.com
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule: "upsert after upserting pkgi"
spec:
  group: services.apps.tanzu.vmware.com
  versions:
  - name: v1alpha1
  names:
    kind: ClusterInstanceClass
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: compositions.apiextensions.crossplane.io
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule: "upsert after upserting pkgi"
spec:
  group: apiextensions.crossplane.io
  versions:
  - name: v1
  names:
    kind: Composition
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: compositeresourcedefinitions.apiextensions.crossplane.io
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule: "upsert after upserting pkgi"
spec:
  group: apiextensions.crossplane.io
  versions:
  - name: v1
  names:
    kind: CompositeResourceDefinition
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: providers.pkg.crossplane.io
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule: "upsert after upserting pkgi"
spec:
  group: pkg.crossplane.io
  versions:
  - name: v1
  names:
    kind: Provider
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule: "upsert after upserting pkgi"
spec:
  group: cert-manager.io
  versions:
  - name: v1
  names:
    kind: Certificate
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule: "upsert after upserting pkgi"
spec:
  group: cert-manager.io
  versions:
  - name: v1
  names:
    kind: Issuer
